apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: event-scraper
build:
  artifacts:
  - image: api
    context: api
    docker:
      dockerfile: Dockerfile
  - image: grpc-server
    context: api
    docker:
      dockerfile: Dockerfile
  - image: mq-handler
    context: api
    docker:
      dockerfile: Dockerfile
  - image: scraper
    context: scraper
    docker:
      dockerfile: Dockerfile
  - image: auth-service
    context: user
    docker:
      dockerfile: Dockerfile
  - image: user-service
    context: user
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment/k8s/api/deployment.yaml
    - deployment/k8s/grpc_server/grpc-deployment.yaml
    - deployment/k8s/mq_handler/mq-handler-deployment.yaml
    - deployment/scraper/deployment.yaml
    - deployment/user/deployment.yaml
    - deployment/auth/auth-deployment.yaml
portForward:
- resourceType: service
  resourceName: api
  port: 8087
- resourceType: service
  resourceName: grpc-server
  port: 50051
- resourceType: service
  resourceName: mq-handler
  port: 8091
- resourceType: service
  resourceName: scraper
  port: 8096
- resourceType: service
  resourceName: user-service
  port: 8089
- resourceType: service
  resourceName: auth-service
  port: 8109
