apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: es-postgres
  namespace: default

spec:

  replicas: 1
  image: postgres:14.1
  customConfig: es-postgres-conf

  database:
    size: 100Mi

  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: es-postgres-secret
          key: superUserPassword

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: es-postgres-secret
          key: replicationUserPassword