apiVersion: v1
kind: Service
metadata:
  name: scraper
  labels:
    app: scraper
spec:
  ports:
  - port: 8096
    protocol: TCP
  clusterIP: None
  selector:
    app: scraper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  labels:
    app: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: scraper
        env:
          - name: ENV
            value: prod
          - name: SECRET_PROD
            value: secret
          - name: AMPQ_URI_PROD
            value: amqp://default_user_HtEoSGNCH1u7v9Mgn4d:2Q2CMMTNKPj1xCmQ-wGzsGSAy2k_C7Uf@esmq
          - name: CONSUMER_TAG_PROD
            value: "consumer-1"
          - name: EXCHANGE_NAME_PROD
            value: "events"
          - name: GRPC_ADDR_PORT_PROD
            value: "50051"
          - name: QUEUE_NAME_PROD
            value: "delete-queue"
          - name: ROUTING_KEY_PROD
            value: "routing-key"
          - name: BILETIX_URL_PROD
            value: "https://www.biletix.com/solr/tr/select/"
          - name: PASSO_URL_PROD
            value: "https://ticketingweb.passo.com.tr/api/passoweb/allevents"
          - name: GRPC_ADDR_PROD
            value: grpc-server
          - name: SCHEDULE_ARRAY_PROD
            value: '[{"provider":0,"timeType":1,"timeCount":1,"category":0,"datePeriod":0,"city":"İstanbul"},{"provider":1,"timeType":1,"timeCount":1,"category":0,"datePeriod":0,"city":"101"}]'